title: Jekyll Demo
email: j2arcidiacono@outlook.com
description: >-
  Una demo de como hacer un blog en Jekyll
baseurl: "/jekyll-config"
domain: mokocchi.github.io
url: "http://mokocchi.github.io/jekyll-config"
twitter_username: mokonahyuu
github_username:  mokocchi

theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-paginate