title: Jekyll Demo
email: j2arcidiacono@outlook.com
description: >-
  Una demo de como hacer un blog en Jekyll
baseurl: "/jekyll-demo"
domain: mokocchi.github.io
url: "http://mokocchi.github.io/jekyll-demo"
twitter_username: mokonahyuu
github_username:  mokocchi
paginate: 5
paginate_path: "/page:num/"
show_excerpts: true

theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-paginate